# Generated by Django 2.2.24 on 2025-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(1, 'Новостройка'), (0, 'Старое здание')], null=True, verbose_name='Новостройка'),
        ),
    ]
