# Generated by Django 2.2.24 on 2025-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250316_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(1, 'Да'), (0, 'Нет')], default=False, verbose_name='Новостройка'),
        ),
    ]
