# Generated by Django 2.2.24 on 2025-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20250316_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='appartment',
            new_name='apartment',
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
