# Generated by Django 5.1.7 on 2025-03-18 17:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер владельца')),
                ('owner_correct_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца')),
                ('apartaments', models.ManyToManyField(related_name='owner_apartaments', to='property.flat')),
            ],
        ),
    ]
