# Generated by Django 5.1.7 on 2025-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='apartaments',
            field=models.ManyToManyField(related_name='owner_apartaments', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
