# Generated by Django 3.2.25 on 2025-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_flat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='apartaments',
            field=models.ManyToManyField(related_name='owners_list', through='property.FlatOwnership', to='property.Flat'),
        ),
    ]
