# Generated by Django 3.2.25 on 2025-04-05 09:38

from django.db import migrations


def populate_ownership(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    FlatOwnership = apps.get_model('property', 'FlatOwnership')

    # Проверим, есть ли в Flat поле owners как строка (старый формат)
    for flat in Flat.objects.all():
        # Пытаемся получить имя владельца из старого текстового поля
        raw_owner_name = getattr(flat, 'owners', None)  # если было строковое поле
        if raw_owner_name and isinstance(raw_owner_name, str):
            # Найдём или создадим владельца по имени
            owner, _ = Owner.objects.get_or_create(owner=raw_owner_name.strip())

            # Создаём связь в FlatOwnership
            FlatOwnership.objects.get_or_create(flat=flat, owner=owner)
            print(f"[+] Добавлен {owner.owner} -> Flat ID {flat.id}")
        else:
            print(f"[ ] Квартира {flat.id} без владельца")

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_owner_apartaments'),
    ]

    operations = [
        migrations.RunPython(populate_ownership)
    ]
