# Generated by Django 3.2.25 on 2025-04-05 10:07

from django.db import migrations

def populate_ownership(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    FlatOwnership = apps.get_model('property', 'FlatOwnership')

    for flat in Flat.objects.all():
        if flat.owner:  # если в старом поле owner есть имя
            owner_name = flat.owner.strip()
            try:
                owner = Owner.objects.filter(owner=owner_name).first()
                if owner:
                    FlatOwnership.objects.get_or_create(flat=flat, owner=owner)
                else:
                    print(f'⚠️ Владелец "{owner_name}" не найден в Owner — квартира id={flat.id}')
            except Exception as e:
                print(f'❌ Ошибка при обработке квартиры id={flat.id}: {e}')

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_add_data_owner_flat'),
    ]

    operations = [
        migrations.RunPython(populate_ownership),
    ]
