# Generated by Django 3.2.25 on 2025-04-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_add_data_owner_flat_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
